availability_zone = "eu-de-01"
scenario          = "csm_controller"
ecs_flavor        = "s2.large.2"
ecs_image         = "Debian_csm_test_host"
network_cidr      = "192.168.0.0/16"
kms_key           = "kms_key"
