scenario = "autoscaling_monitoring"
ecs_flavor = "s2.large.2"
bastion_image = "Standard_Debian_10_latest"
ecs_image = "KPI_Scn4_host_image"
addr_3_octets = "192.168.5"
availability_zone = "eu-de-01"
region = "eu-de"