target_availability_zone    = "eu-de-01"
initiator_availability_zone = "eu-de-03"
scenario                    = "iscsi"
ecs_flavor                  = "s2.large.2"
ecs_image                   = "Standard_Debian_10_latest"
network_cidr                = "192.168.0.0/16"
