region            = "eu-de"
tenant_name       = ""
availability_zone = "eu-de-01"
domain_name       = ""
postfix           = "scn3"
ecs_flavor        = "s2.large.2"
ecs_image         = "Standard_Debian_9_latest"