variable "subnet_cidr" {}
variable "ecs_flavor" {}
variable "ecs_image" {}
variable "subnet_id" {}
variable "network_id" {}
variable "router_id" {}
variable "scenario" {}
variable "key_pair" {}
variable "region" {}
variable "availability_zone" {}
variable "disc_volume" {}
