region                      = "eu-de"
tenant_name                 = ""
target_availability_zone    = "eu-de-01"
initiator_availability_zone = "eu-de-03"
domain_name                 = ""
postfix                     = "scn3_5"
ecs_flavor                  = "s2.large.2"
ecs_image                   = "Standard_Debian_9_latest"