variable "disk_volume" {}
variable "target_availability_zone" {}
variable "initiator_availability_zone" {}
variable "scenario" {}
variable "ecs_flavor" {}
variable "ecs_image" {}
variable "volume_type" {}
variable "key_pair" {}
variable "subnet_id" {}
variable "network_id" {}
variable "router_id" {}
variable "net_address" {}
