{
 "title": "LB_DOWN",
 "tags": [ "scn1-test2" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Re-balance test",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "success-total",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_down",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ok", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "success $tag_server",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "lb_down",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ok", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "fail",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lb_down",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ok", "operator": "=", "value": "False" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_down",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Re-balance",
   "type": "alertlist",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Script status",
   "type": "graph",
   "description": "Show that test script working properly",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "ok",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lb_down_test",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "reason", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Node not shut down",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lb_down_test",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "reason", "operator": "=", "value": "multiple_nodes" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lb_down_test",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}