{
 "title": "LB_LOAD_high_res",
 "tags": [ "scn1-test1" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Load balancer time distribution (overall)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_server / OTC",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_timing",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^basic-\\d/" },
      { "condition": "AND", "key": "client", "operator": "=~", "value": "/^80\\..+/" }
     ]
    },
    {
     "alias": "$tag_server / AWS",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_timing",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^basic-\\d/" },
      { "condition": "AND", "key": "client", "operator": "=~", "value": "/^34\\..+/" }
     ]
    },
    {
     "alias": "$tag_server / Azure",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_timing",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^basic-\\d/" },
      { "condition": "AND", "key": "client", "operator": "=~", "value": "/^40\\..+/" }
     ]
    }
   ]
  },
  {
   "title": "Request timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Azure client",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "lb_timeout",
     "select": [
      [
       { "params": [ "timeout" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "client", "operator": "=", "value": "40.113.8.30" }
     ]
    },
    {
     "alias": "AWS client",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "lb_timeout",
     "select": [
      [
       { "params": [ "timeout" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "client", "operator": "=", "value": "34.245.34.71" }
     ]
    },
    {
     "alias": "OTC client",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "lb_timeout",
     "select": [
      [
       { "params": [ "timeout" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "client", "operator": "=", "value": "80.158.48.21" }
     ]
    }
   ]
  },
  {
   "title": "Node request distribution (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lb_timing",
     "query": "SELECT count(\"elapsed\") FROM \"lb_timing\" WHERE $timeFilter GROUP BY time(30s), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^basic-\\d/" }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "basic-0" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "basic-1" }
     ]
    }
   ]
  },
  {
   "title": "Network bytes recv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_interface / $tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ens3" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^basic-\\d/" }
     ]
    }
   ]
  },
  {
   "title": "Network bytes sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_interface / $tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ens3" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^basic-\\d/" }
     ]
    }
   ]
  },
  {
   "title": "Network utilization (open sockets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "tcp_activeopens" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "basic-0" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "basic-1" }
     ]
    }
   ]
  }
 ]
}